shellcheck: add a default case with an error exit.
Change-Id: Ic94f96c60d59e1d245de65aa18c3cc7857e3b5a0

diff --git a/sp_variant.sh.j2 b/sp_variant.sh.j2
--- a/sp_variant.sh.j2
+++ b/sp_variant.sh.j2
@@ -346,6 +346,11 @@ cmd_repo_add()
 			{% endif %}
 			;;
 		{% endfor %}
+
+		*)
+			echo "Internal error: '$variant' should be recognized at this point" 1>&2
+			exit 1
+			;;
 	esac
 
 	install -o root -g root -m 755 -- "$0" /usr/sbin/sp_variant
